/* Config.hh. Generated by CMake for ignition-math. */

/* Version number */
#define IGNITION_MATH_MAJOR_VERSION 
#define IGNITION_MATH_MINOR_VERSION 
#define IGNITION_MATH_PATCH_VERSION 

#define IGNITION_MATH_VERSION "4.0"
#define IGNITION_MATH_VERSION_FULL "4.0.0"

#define IGNITION_MATH_VERSION_NAMESPACE v4

#define IGNITION_MATH_VERSION_HEADER "Ignition math, version 4.0.0\nCopyright (C) 2014 Open Source Robotics Foundation.\nReleased under the Apache 2.0 License.\n\n"

/* #undef IGNITION_MATH_BUILD_TYPE_PROFILE */
/* #undef IGNITION_MATH_BUILD_TYPE_DEBUG */
/* #undef IGNITION_MATH_BUILD_TYPE_RELEASE */
