// Generated by gencpp from file localizer_dwm1001/askPositionResponse.msg
// DO NOT EDIT!


#ifndef LOCALIZER_DWM1001_MESSAGE_ASKPOSITIONRESPONSE_H
#define LOCALIZER_DWM1001_MESSAGE_ASKPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace localizer_dwm1001
{
template <class ContainerAllocator>
struct askPositionResponse_
{
  typedef askPositionResponse_<ContainerAllocator> Type;

  askPositionResponse_()
    : posX(0.0)
    , posY(0.0)  {
    }
  askPositionResponse_(const ContainerAllocator& _alloc)
    : posX(0.0)
    , posY(0.0)  {
  (void)_alloc;
    }



   typedef double _posX_type;
  _posX_type posX;

   typedef double _posY_type;
  _posY_type posY;





  typedef boost::shared_ptr< ::localizer_dwm1001::askPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localizer_dwm1001::askPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct askPositionResponse_

typedef ::localizer_dwm1001::askPositionResponse_<std::allocator<void> > askPositionResponse;

typedef boost::shared_ptr< ::localizer_dwm1001::askPositionResponse > askPositionResponsePtr;
typedef boost::shared_ptr< ::localizer_dwm1001::askPositionResponse const> askPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localizer_dwm1001::askPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localizer_dwm1001::askPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::localizer_dwm1001::askPositionResponse_<ContainerAllocator1> & lhs, const ::localizer_dwm1001::askPositionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.posX == rhs.posX &&
    lhs.posY == rhs.posY;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::localizer_dwm1001::askPositionResponse_<ContainerAllocator1> & lhs, const ::localizer_dwm1001::askPositionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace localizer_dwm1001

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::localizer_dwm1001::askPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localizer_dwm1001::askPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localizer_dwm1001::askPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localizer_dwm1001::askPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localizer_dwm1001::askPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localizer_dwm1001::askPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localizer_dwm1001::askPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b1d3450d6d4d498c9d5ff2b8d4df2f51";
  }

  static const char* value(const ::localizer_dwm1001::askPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb1d3450d6d4d498cULL;
  static const uint64_t static_value2 = 0x9d5ff2b8d4df2f51ULL;
};

template<class ContainerAllocator>
struct DataType< ::localizer_dwm1001::askPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localizer_dwm1001/askPositionResponse";
  }

  static const char* value(const ::localizer_dwm1001::askPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localizer_dwm1001::askPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 posX\n"
"float64 posY\n"
"\n"
;
  }

  static const char* value(const ::localizer_dwm1001::askPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localizer_dwm1001::askPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.posX);
      stream.next(m.posY);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct askPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localizer_dwm1001::askPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::localizer_dwm1001::askPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "posX: ";
    Printer<double>::stream(s, indent + "  ", v.posX);
    s << indent << "posY: ";
    Printer<double>::stream(s, indent + "  ", v.posY);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZER_DWM1001_MESSAGE_ASKPOSITIONRESPONSE_H
