// Generated by gencpp from file localizer_dwm1001/askPosition.msg
// DO NOT EDIT!


#ifndef LOCALIZER_DWM1001_MESSAGE_ASKPOSITION_H
#define LOCALIZER_DWM1001_MESSAGE_ASKPOSITION_H

#include <ros/service_traits.h>


#include "askPositionRequest.h"
#include "askPositionResponse.h"


namespace localizer_dwm1001
{

struct askPosition
{

typedef askPositionRequest Request;
typedef askPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct askPosition
} // namespace localizer_dwm1001


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::localizer_dwm1001::askPosition > {
  static const char* value()
  {
    return "b1d3450d6d4d498c9d5ff2b8d4df2f51";
  }

  static const char* value(const ::localizer_dwm1001::askPosition&) { return value(); }
};

template<>
struct DataType< ::localizer_dwm1001::askPosition > {
  static const char* value()
  {
    return "localizer_dwm1001/askPosition";
  }

  static const char* value(const ::localizer_dwm1001::askPosition&) { return value(); }
};


// service_traits::MD5Sum< ::localizer_dwm1001::askPositionRequest> should match
// service_traits::MD5Sum< ::localizer_dwm1001::askPosition >
template<>
struct MD5Sum< ::localizer_dwm1001::askPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::localizer_dwm1001::askPosition >::value();
  }
  static const char* value(const ::localizer_dwm1001::askPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::localizer_dwm1001::askPositionRequest> should match
// service_traits::DataType< ::localizer_dwm1001::askPosition >
template<>
struct DataType< ::localizer_dwm1001::askPositionRequest>
{
  static const char* value()
  {
    return DataType< ::localizer_dwm1001::askPosition >::value();
  }
  static const char* value(const ::localizer_dwm1001::askPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::localizer_dwm1001::askPositionResponse> should match
// service_traits::MD5Sum< ::localizer_dwm1001::askPosition >
template<>
struct MD5Sum< ::localizer_dwm1001::askPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::localizer_dwm1001::askPosition >::value();
  }
  static const char* value(const ::localizer_dwm1001::askPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::localizer_dwm1001::askPositionResponse> should match
// service_traits::DataType< ::localizer_dwm1001::askPosition >
template<>
struct DataType< ::localizer_dwm1001::askPositionResponse>
{
  static const char* value()
  {
    return DataType< ::localizer_dwm1001::askPosition >::value();
  }
  static const char* value(const ::localizer_dwm1001::askPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCALIZER_DWM1001_MESSAGE_ASKPOSITION_H
